config/routes.rb
Rails.application.routes.draw do
  resources :friends
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

  <div class="field">
    <%= form.text_field :first_name, class:"w-full text-sm border border-solid border-gray-400 p-2 mb-8 rounded focus:outline-none", placeholder: "First name"%>
  </div>

  <div class="field">
    <%= form.text_field :last_name, class:"w-full text-sm border border-solid border-gray-400 p-2 mb-8 rounded focus:outline-none", placeholder: "Last name"%>
  </div>

  <div class="field">
    <%= form.text_field :email, class:"w-full text-sm border border-solid border-gray-400 p-2 mb-8 rounded focus:outline-none", placeholder: "E-mail"%>
  </div>

  <div class="field">
    <%= form.text_field :phone, class:"w-full text-sm border border-solid border-gray-400 p-2 mb-8 rounded focus:outline-none", placeholder: "Phone"%>
  </div>

  <div class="field">
    <%= form.text_field :twitter, class:"w-full text-sm border border-solid border-gray-400 p-2 mb-8 rounded focus:outline-none", placeholder: "Twitter"%>
  </div>

  <div class="actions">
    <%= form.submit class: "w-full mb-4 p-2 mx-auto rounded text-sm bg-gray-700 text-white cursor-pointer focus:outline-none hover:bg-gray-800 md:px-2 lg:mx-0 lg:w-1/6"%>
  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="container mx-auto">
    <h1 class="text-2xl w-full text-gray-700 my-4 text-center md:w-auto md:text-left">Editing Friend</h1>

    <%= render 'form', friend: @friend %>

    <div class="flex items-center w-full lg:w-1/6">
        <%= link_to 'Show', @friend, class: "block text-center p-2 w-full mx-auto rounded bg-gray-500 text-white text-sm lg:mr-2 hover:bg-gray-600 focus:outline-none" %>
        <%= link_to 'Back', friends_path, class: "block text-center p-2 w-full mx-auto rounded bg-gray-700 text-white text-sm hover:bg-gray-800 focus:outline-none" %>
    </div>
</div>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container mx-auto">
  <h1 class="text-2xl w-full text-gray-700 my-4 text-center md:w-auto md:text-left">Friends</h1>
  <div class="w-full overflow-x-auto mb-4">
    <table class="w-full border-collapse rows border border-solid border-gray-300">
      <thead class="border-t border-b border-gray-300 border-solid text-left text-xs bg-gray-700 text-white lg:text-sm">
        <tr>
          <th class="px-8 py-2.5">First name</th>
          <th class="px-8 py-2.5">Last name</th>
          <th class="px-8 py-2.5">Email</th>
          <th class="px-8 py-2.5">Phone</th>
          <th class="px-8 py-2.5">Twitter</th>
          <th colspan="3" class="px-8 py-2.5"></th>
        </tr>
      </thead>

      <tbody class="border-t border-b border-gray-300 border-solid text-left text-black text-xs lg:text-sm">
        <% @friends.each do |friend| %>
          <tr class="border-t border-b border-gray-300 border-solid2 text-left">
            <td class="px-8 py-2.5"><%= friend.first_name %></td>
            <td class="px-8 py-2.5"><%= friend.last_name %></td>
            <td class="px-8 py-2.5"><%= friend.email %></td>
            <td class="px-8 py-2.5"><%= friend.phone %></td>
            <td class="px-8 py-2.5"><%= friend.twitter %></td>
            <td class="px-8 py-2.5"><%= link_to 'Show', friend, class: "text-blue-500 font-bold hover:text-blue-600"%></td>
            <td class="px-8 py-2.5"><%= link_to 'Edit', edit_friend_path(friend), class: "text-blue-500 font-bold hover:text-blue-600" %></td>
            <td class="px-8 py-2.5"><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-blue-500 font-bold hover:text-blue-600" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

    <%= link_to 'New Friend', new_friend_path, class: "block w-full mx-auto text-center text-xs py-2 rounded bg-gray-700 text-white lg:mx-0 lg:text-sm lg:ml-auto lg:w-1/6 hover:bg-gray-800" %>
</div>

app/views/friends/new.html.erb
<div class="container mx-auto">
<h1 class="text-2xl w-full text-gray-700 my-4 text-center md:w-auto md:text-left">New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path, class: "block text-center w-full mx-auto p-2 text-sm rounded bg-gray-500 text-white lg:mx-0 lg:w-1/6 hover:bg-gray-600"%>
</div>

app/views/friends/show.html.erb
<div class="container mx-auto">
  <div class="bg-gray-200 px-8 p-16 w-full rounded">
    <p id="notice"><%= notice %></p>

    <div class="w-full flex items-center justify-center md:justify-start mb-4">
      <p class="text-5xl font-normal mr-2 text-gray-700">
        <%= @friend.first_name %>
        <%= @friend.last_name %>
      </p>
    </div>

    <div class="w-full flex items-center justify-center mb-4 text-base text-gray-600 md:text-lg md:justify-start">
      <p class="mr-2">
        <%= @friend.email %> |
        <%= @friend.phone %> |
        <%= @friend.twitter %>
      </p>
    </div>

    <div class="border-t border-solid border-gray-400 mb-8"></div>

    <div class=" w-full md:flex md:items-center md:w-1/5">
      
      <%= link_to 'Edit', edit_friend_path(@friend), class: " block text-center p-2 w-full mx-auto rounded bg-gray-500 mr-2 mb-2 text-white text-sm md:mb-0 hover:bg-gray-600 focus:outline-none focus:outline-none" %>

      <%= link_to 'Back', friends_path, class: "block text-center p-2 w-full mx-auto rounded bg-gray-700 text-white text-sm hover:bg-gray-800 focus:outline-none" %>
    </div>
  </div>
</div>

app/views/home/_header.html.erb
<header class="w-full bg-gray-700 text-gray-100 px-16 py-4 md:px-8 md:py-2">
    <div class="container mx-auto md:flex md:items-center">
        <h1 class="w-full text-2xl text-center font-bold mb-2 md:w-auto"><%= link_to 'Friend app', root_path %></h1>
        <nav class="w-full mb-2 text-center md:flex md:items-center md:ml-16 md:w-auto">
            <%= link_to 'Friends', friends_path, class: "text-sm lg:text-md text-gray-300 hover:text-white"%>
            <%= link_to 'Add Friend', new_friend_path, class: "ml-4 text-sm lg:text-md text-gray-300 md:ml-8 hover:text-white"%>
        </nav>
        <div class="flex ml-auto">
            <input type="text" class="w-full px-2 py-1 text-base text-black rounded md:ml-auto md:w-1/2 lg:w-4/5">
            <button class="ml-2 px-2 text-center border border-solid border-green-600 rounded text-green-600 focus:outline-none hover:bg-green-600 hover:text-white">Search</button>
        </div>
    </div>  
</header>

app/views/home/about.html.erb
<h1 class="text-blue-500">About us!</h1>

app/views/home/index.html.erb
<div class="container mx-auto">
    <h1 class="text-2xl w-full text-gray-700 my-4 text-center md:w-auto md:text-left">About the project</h1>
    <p class="text-justify">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eu velit ipsum. 
        Mauris ac justo eu mi mollis dapibus ac vel magna. Fusce ullamcorper blandit accumsan. In aliquam magna erat.
        Quisque felis turpis, rutrum ut egestas eu, blandit non orci. Cras posuere luctus sollicitudin. Quisque orci magna,
        condimentum eget lorem gravida, dictum pharetra neque. Nam dapibus nisi velit, a tincidunt augue ullamcorper ut.
        Fusce consequat nunc in consectetur accumsan. Aliquam porta placerat rutrum. Mauris pharetra nisi quis ipsum ullamcorper,
        vel tristique nunc fermentum. Suspendisse egestas semper mauris, sed interdum massa blandit nec.
        Nunc vitae tincidunt leo. Phasellus varius at nisi at venenatis. Vivamus pharetra lectus diam, a eleifend diam efficitur id.
        Integer tincidunt sollicitudin auctor. Donec lobortis consectetur placerat. Curabitur tincidunt dapibus dui a rhoncus.
        Nunc tellus purus, tempus at venenatis nec, efficitur et augue. 
    </p>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%=  stylesheet_pack_tag  'application',  media: 'all',  'data-turbolinks-track': 'reload'  %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>

    <main class="box-border w-full p-4 md:py-8 md:px-16">
      <%= yield %>
    </main>
  </body>
</html>